replicaCount: 2

image:
  repository: your-docker-repo/hexagonal-calculator
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: calculator.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
