apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hexagonal-calculator.fullname" . }}
  labels:
    {{- include "hexagonal-calculator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hexagonal-calculator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | default (include "hexagonal-calculator.name" .) }}
  template:
    metadata:
      labels:
        {{- include "hexagonal-calculator.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
