{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ include "hexagonal-calculator.fullname" . }}{{ end }}
  labels:
    {{- include "hexagonal-calculator.labels" . | nindent 4 }}
{{- end }}
