apiVersion: v1
kind: Service
metadata:
  name: {{ include "hexagonal-calculator.fullname" . }}
  labels:
    {{- include "hexagonal-calculator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "hexagonal-calculator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | default (include "hexagonal-calculator.name" .) }}
